[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TAPAS"
version = "0.0.1"
description = "This is the initial repo for the complexity72h"
authors = [
  { name = "Complexity72h Authors" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "graph-tools>=1.14",
    "igraph>=0.11.9",
    "ipython",
    "jupyterlab",
    "loguru",
    "matplotlib",
    "notebook",
    "numpy",
    "openpyxl>=3.1.5",
    "pandas",
    "pip",
    "python-dotenv",
    "ruff",
    "scikit-learn",
    "tqdm",
    "typer",
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["TAPAS"]
include = ["pyproject.toml", "TAPAS/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["TAPAS"]
force-sort-within-sections = true

